learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
"""Burada herhangi bir çalışan fonksiyon olmamasına rağmen urlpatterns nasıl
eşleşen url'i views.py'ye gönderiyor. Bu alien_invasion'daki settings.py gibi
çalışmıyor mu?"""
"""Defines URL patterns for learning_logs."""

from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Home page
    # views.index() olması gerekmiyor mu index() bir fonksiyon çünkü.
    path('', views.index, name='index'),
    # Page that shows all topics.
    path('topics/', views.topics, name='topics'),
    # Detail page for a single topic.
    path('topics/<int:topic_id>', views.topic, name='topic'),
    # Page for adding a new topic
    # İyi de her kullanıcı için aynı url olmuyor mu? Bu anlamsız bir çakışma 
    #durumu değil mi?(new_topic/<int:user_id> gibi olması gerekmiyor mu?)
    path('new_topic/', views.new_topic, name='new_topic'),
    # Page for adding a new entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Page for editing an entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

"""
NOTE
There’s a subtle but important dif erence between topic.id and topic_id. The
expression topic.id examines a topic and retrieves the value of the corresponding
ID. The variable topic_id is a reference to that ID in the code. If you run into
errors when working with IDs, make sure you’re using these expressions in the
appropriate ways.
"""

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    #Bu neden '' boş?
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    # Bunda neden views yazıyoruz, defaultu yok mu?
    # http://localhost:8000/users/register/ ile eşleşmesi için gerekli olan
    #users/ nereden geliyor?
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    """A topic the user is learning about."""
    # Bunlar neden self.text değil de direkt text?
    # __init__ neden yok, normal classlarda da olması zorunlu değil mi? Dene.
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    # Direkt def str(self) yada __init__(self) diyebilir miydik dene?
    #ve neden __init__ yerine __str__ tercih edilmiş?
    def __str__(self):
        """Return a string representation of the model."""
        return self.text


class Entry(models.Model):
    """Something specific learned about a topic."""

    topic = models.ForeignKey(Topic, 
            on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    # Neden Meta sınıfından bir örneği, bir nitelik olarak eklemek yerine
    #direkt sınıf içinde sınıf tanımladık?
    # Bu Meta bende çalışmıyor? neden?
    class Meta:
        """docstring'i neden yok?"""
        # verbose_name_plural özel bir değişken mi?
        # 'entries2' dğerinin ilk harfi otomatik Büyük yazılıyor ya istemiyorsak?
        verbose_name_plural ='entries'

    def __str__(self):
        """Return a string representation of the model."""
        if len(self.text) < 50:
            return f"{self.text}"
            # text 50'den kısa ise ve nokta ile bitiyorsa 4 . görünecek?
            # Bende neden ilk 50 karakter gözükmüyor?
        return f"{self.text[:50]}..."

learning_logs/forms.py
from django import forms

from  .models import Topic, Entry

class TopicForm(forms.ModelForm):

    class Meta:
        # Bu modellerin parantezleri nerede? neden yok? Topic()
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):

    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

def index(request):
    """The home page for Learning Log."""
    # 'learning_logs/index.html' bu url patterni neden learning_logs ile başlıyor?
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """Show all topics."""
    # store the resulting queryset in topics.
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    # Detail page for a single topic.
    #topic = Topic.objects.get(id=topic_id)
    topic = get_object_or_404(Topic, id=topic_id)
    _check_topic_owner(topic.owner, request.user)

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            # conmmit=False araştır.
            new_topic = form.save(commit=False)
            #new_topic = form.save()
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')

    # Display a blank or invalid form.
    context = {'form': form}
    # An invalid form will include some default error messages to help the user 
    #submit acceptable data. _Hani nerede?
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = get_object_or_404(Topic, id=topic_id)
    _check_topic_owner(topic.owner, request.user)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)

    # Display a blank or invalid form.
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = get_object_or_404(Entry, id=entry_id)
    topic = entry.topic
    _check_topic_owner(topic.owner, request.user)

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        #ne demek initial request?
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            # Buradaki girdi nasıl halihazırda doğru konuyla ilişkili?
            form.save()
            # Burada neden new_entry'deki gibi topic_id=topic_id değil?
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

# Bir class içerinde olmamasına rağmen helper method yerine helper fonksiyon
#tanımlanabiliyor mu? Cevap evet ise aşağıdaki kullanım doğrumu ?
# Bu kullanımın söyle bir yetersizliği var; eğer henüz oluşturulmamış-db'de 
#yer almayan birşeyi çağırırsak Http404 yerine bulunmadığına-var olmadığına- 
#dair bir hata dönderiliyor. Buna önlem al.
def _check_topic_owner(topic_owner, request_user):
    """
    We make sure the user associated with a topic matches the currently 
    logged in user.
    """
    # Make sure the topic belongs to the current user.
    if topic_owner != request_user:
        # direkt return demekle tam olarak ne farkı var?
        # raise ne? Kendi içinde mi return'ü var topic()'in
        # if dışına veya else bir return yada başka bir raise eklemek bu durum 
        #için mantıklı mı?
        raise Http404

learning_logs/templates/learning_logs/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=">
    <title>Learning Log</title>

    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
                data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" 
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'learning_logs:topics' %}">Topics</a>
                    </li>
                </ul> <!-- End of links on left side of navbar -->

                <!-- Account-related links -->
                <ul class="navbar-nav ms-auto mb-2 mb-md-0">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <span class="navbar-text me-2">Hello, {{ user.username }}.</span>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:login' %}">Log in</a>
                        </li>
                    {% endif %}
                </ul> <!-- End of account-related links -->

                {% if user.is_authenticated %}
                    <form action="{% url 'accounts:logout' %}" method='post'>
                        {% csrf_token %}
                        <button name='submit' class='btn btn-outline-secondary btn-sm'>
                            Log out</button>
                    </form>
                {% endif %}

            </div> <!-- Closes collapsible parts of navbar -->
        </div> <!-- Closes navbar's container -->
    </nav> <!-- End of navbar -->

    <main class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>

</body>
</html>




<!--
<p>
    <a href="{#% url 'learning_logs:index' %}">Learning Log</a> -
    <a href="{#% url 'learning_logs:topics' %}">Topics</a> - 
    {#% if user.is_authenticated %}
        Hello, {{# user.username }}.
        <a href="{#% url 'users:logout' %}">Log out</a>
    {#% else %}
        <a href="{#% url 'users:register' %}">Register</a> - 
        <a href="{#% url 'users:login' %}">Log in</a>
    {#% endif %}
</p>

{#% block content %}{% endblock content %}
-->

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <p>Topic: <a href="{% url 'learning_logs:edit_entry' topic.id %}">{{ topic }}</a></p>
{% endblock page_header %}

{% block content %}
    <p>Edit entry:</p>
    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name='submit' class="btn btn-primary">Save changes</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
<!--- buraya neden load bstrap4 demedik, eğer base.html'den alıyorsa diğerlerine 
    neden ekliyoru<? --->

{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">Track your learning.</h1>

        <p class="lead">Make your own Learning Log, and keep a list of the 
            topics you're learning about. Whenever you learn something new 
        about a topic, make an entry summarizing what you've learned.</p>

        {% if user.is_authenticated %}
            <!-- ekleme yapılabilinir --->
        {% else %}
        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" 
            role="button">Register &raquo;</a>
        {% endif %}
    </div>
{% endblock page_header %}

<!--- if oturum açtıysa eklenmesi gerekiyor
ya register yerine topics ya son topic ya best topic
yada ayarlar-ayarlara kullanıcıyı böyle göndermeye gerek yok --->

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <p>Topic: <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
{% endblock page_header %}

{% block content %}
    <p>Add a new entry:</p>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post' class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name='submit' class="btn btn-primary">Add entry</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block content %}
    <p>Add a new topic:</p>

    <!-- class="form" ne işe yarıyor, çıkartmak birşey değiştirmiyor diye gözüküyor -->
    <form action="{% url 'learning_logs:new_topic' %}" method='post' class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        <!-- {#% buttons %} ve endbutton'u yazmayıp, load bootstrap eklemesem 
            bile aynı çalışıyor -->
        {% buttons %}
            <button name="submit" class="btn btn-primary">Add topic</button> 
        {% endbuttons %}
    </form>

{% endblock content %}
<!--
Projenin stilsiz hali base.html dışında çok daha iyiydi
<button name="submit">Add topic</button>
-->
<!--
login.html'de bunun olmasının sebebi login views'i bize hazır-bize ait- olmadığı 
için mi? 
    <input type="hidden" name="next" value="{#% url 'learning_logs:topics' %}">
-->

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
    <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}

    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
    </p>
    <ul>
        {% for entry in entries %}
            <div class="card mb-3">
                <h4 class="card-header">
                    {{ entry.date_added|date:'M d-D, Y H:i' }}
                    <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
                        edit entry</a></small>
                </h4>
                <div class="card-body">
                    {{ entry.text|linebreaks }}
                </div>
            </div>

        {% empty %}
            <p>There are no entries for this topic yet.</p>
        {% endfor %}
    </ul>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
<!---
    We don’t need the {% load bootstrap4 %} tag, because we’re not using any
custom bootstrap4 template tags in this file.
    O zaman custom bootstrap4 template tags?
--->

{% block page_header %}
    <h1>Topics</h1>
{% endblock page_header %}

{% block content %}

    <ul>
        {% for topic in topics %}
            <li><h3>
                <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
            </h3></li>
        {% empty %}
            <li><h3>No topics have been added yet.</h3></li>
        {% endfor %}
    </ul>

    <h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a></h3>

{% endblock content %}